config/routes.rb
Rails.application.routes.draw do
  resources :alunos do
    collection { post :import }
    collection { get :export }
  end
  devise_for :users
  resources :cursos do
    collection { post :import }
    collection { get :export }
  end
  resources :universidades do
    collection { post :import }
    collection { get :export }
  end
  root 'universidades#index'
end

app/models/universidade.rb
class Universidade < ActiveRecord::Base
require 'csv'
has_many :cursos

  validates :nome, presence:true
  validates :uf, presence:true
  validates :nota_geral, presence:true


def self.import(file)

  CSV.foreach(file.path, headers:true) do |row|
      universidade = find_by_id(row["id"]) || new
      universidade.attributes = row.to_hash.slice(*['id','nome','uf','nota_geral','created_at','updated_at'])
      universidade.save!
  end
end

def self.to_csv

    CSV.generate do |csv|
        csv << column_names
        all.each do |universidade|
            csv << universidade.attributes.values_at(*column_names)
        end
    end

end

end

app/controllers/universidades_controller.rb
class UniversidadesController < ApplicationController
  before_action :set_universidade, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  require 'csv'

  # GET /universidades
  # GET /universidades.json
  def index
    #@universidades = Universidade.order("nota_geral DESC")
    @q = Universidade.ransack(params[:q].try(:merge, m:'or'))
    @q.sorts = 'nota_geral desc' if @q.sorts.empty?
    @universidades = @q.result

    @iesMaiorNota = Universidade.maximum(:nota_geral)
    @iesMenorNota = Universidade.minimum(:nota_geral)

    respond_to do |format|
        format.html
        format.csv {send_data @universidades.to_csv}
    end
  end

  def export
    @universidades = Universidade.all
    respond_to do |format|
        format.html
        format.csv {send_data @universidades.to_csv, filename:'universidades.csv'}
    end
  end

  def import
      Universidade.import(params[:file])
      redirect_to root_url, notice: "Dados do arquivo importados com sucesso!"
  end


    def import_cursos
        Curso.import(params[:file])
        redirect_to root_url, notice: "Dados do arquivo importados com sucesso!"
    end

  # GET /universidades/1
  # GET /universidades/1.json
  def show
    session[:universidade_id] = @universidade.id
    session[:universidade_nome] = @universidade.nome
    session[:universidade_uf] = @universidade.uf
    session[:universidade_nota_geral] = @universidade.nota_geral
    redirect_to cursos_path
  end

  # GET /universidades/new
  def new
    @universidade = Universidade.new
  end

  # GET /universidades/1/edit
  def edit
  end

  def iesMaiorNota
      @iesMaiorNota = Universidade.order(:nota_geral).limit 1
  end

  # POST /universidades
  # POST /universidades.json
  def create
    @universidade = Universidade.new(universidade_params)
    respond_to do |format|
      if @universidade.save
        format.html { redirect_to @universidade, notice: 'IES cadastrada com sucesso!' }
        format.json { render :show, status: :created, location: @universidade }
      else
        format.html { render :new }
        format.json { render json: @universidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /universidades/1
  # PATCH/PUT /universidades/1.json
  def update
    respond_to do |format|
      if @universidade.update(universidade_params)
        format.html { redirect_to @universidade, notice: 'IES atualizada com sucesso!' }
        format.json { render :show, status: :ok, location: @universidade }
      else
        format.html { render :edit }
        format.json { render json: @universidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /universidades/1
  # DELETE /universidades/1.json
  def destroy
    @universidade.destroy
    respond_to do |format|
      format.html { redirect_to universidades_url, notice: 'IES removida com sucesso!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_universidade
      @universidade = Universidade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def universidade_params
      params.require(:universidade).permit(:nome, :uf, :nota_geral)
    end
end

app/helpers/universidades_helper.rb
module UniversidadesHelper
end

app/views/universidades/_form.html.erb
<%= form_for(@universidade) do |f| %>
  <% if @universidade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@universidade.errors.count, "error") %> prohibited this universidade from being saved:</h2>

      <ul>
      <% @universidade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome %>
    <%= f.text_field :nome, class: "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.label :uf,'UF' %>
    <%= f.select :uf, ['AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO'] ,{}, class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :nota_geral %>
    <%= f.text_field :nota_geral, class: "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.submit "Confirmar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/universidades/edit.html.erb
<br/>
<div class="alert alert-warning" role="alert">
  <h3>
    <%= "Alterar dados da IES: #{@universidade.nome} - #{@universidade.uf}"%>
  </h3>
  <%= "Nota geral: #{@universidade.nota_geral}"%>
</div>


<div class="row">
<div class="col-lg-6 col-xs-6">
  <% if user_signed_in? %>
    <%= link_to 'Remover IES', @universidade, method: :delete, class: "btn btn-danger", data: { confirm: 'Você tem certeza?' } %>
  <%end%>
  <br/>
  <br/>
</div>
</div>

<%= render 'form' %>

<%= link_to "Voltar", @universidade, class:"btn btn-warning"%>

app/views/universidades/index.html.erb
<% if flash[:notice] %>
  <br/>
  <div class="alert alert-success" role="alert">
    <%= flash[:notice]%>
  </div>
<%end%>
<br/>
<div class="alert alert-warning" role="alert">
  <h3>
    IES Cadastradas
  </h3>
</div>

<div class="row">

<div class="col-lg-2 col-xs-6">
  <% if user_signed_in? %>
  <p><%= link_to 'Cadastrar IES', new_universidade_path, class: "btn btn-primary"  %></p>
  <%end%>
  <br/>
  <br/>
</div>

<div class="col-lg-3 col-xs-6">
  <% if user_signed_in? %>
  <p><%= link_to 'Download das IES (CSV)', export_universidades_path(format: "csv"), class: "btn btn-primary"  %></p>
  <%end%>
  <br/>
  <br/>
</div>


<div class="col-lg-6 col-xs-6">
  <% if user_signed_in? %>
      <%= form_tag import_universidades_path, multipart:true do %>
        <div class="form-inline">
          <%= file_field_tag :file, class:"form-control" %>
          <%= submit_tag "Importar IES via CSV", class:"btn btn-primary" %>
        </div>
      <%end%>
  <%end%>
  <br/>
  <br/>
</div>


</div>

<div class="row">

  <div class="col-lg-3 col-xs-6">
  <div class="small-box bg-green">
      <div class="inner">
        <h3><%= @iesMaiorNota %><sup style="font-size: 20px"> de 5</sup></h3>
        <p>IES com maior nota</p>
      </div>
    </div>
  </div>
  <div class="col-lg-3 col-xs-6">
  <div class="small-box bg-red">
      <div class="inner">
        <h3><%= @iesMenorNota %><sup style="font-size: 20px"> de 5</sup></h3>
        <p>IES com menor nota</p>
      </div>
    </div>
  </div>
</div>

<%= search_form_for @q do |f| %>
<div class="form-inline">
    <div class="form-group">
      <%= f.label :nome_cont, "Pesquisar por nome:" %>
      <%= f.search_field :nome_cont, class: "form-control"%>
    </div>
    <div class="form-group">
      <%= f.label :nota_geral_cont, "Pesquisar por nota geral:" %>
      <%= f.search_field :nota_geral_cont, class: "form-control"%>
    </div>
    <%= f.submit "Filtrar", class:"btn btn-primary"%>
</div>

<%end%>
<table class="table table-bordered table-striped table-hover">
  <thead>
    <tr>

      <th><%= sort_link(@q, :nome, 'Nome IES', default_order: :asc) %></th>
      <th><%= sort_link(@q,:uf, 'UF')%></th>
      <th><%= sort_link(@q, :nota_geral, 'Nota Geral', default_order: :desc) %></th>
      <th>Acessar</th>
      <% if user_signed_in? %>
      <th>Gerenciar</th>
      <%end%>
    </tr>
  </thead>

  <tbody>
    <% @universidades.each do |universidade| %>
      <tr>
        <td><%= universidade.nome%></td>
        <td><%= universidade.uf %></td>
        <td><%= universidade.nota_geral %></td>
        <td><%= link_to "Detalhes", universidade, class:"btn btn-info"%></td>
        <% if user_signed_in? %>
        <td><%= link_to "Alterar IES", edit_universidade_path(universidade), class:"btn btn-warning"%></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/universidades/new.html.erb
<br/>
<div class="alert alert-warning" role="alert">
  <h3>
    Cadastrar nova IES
  </h3>
</div>

<%= render 'form' %>
<%= link_to "Voltar", universidades_path, class:"btn btn-warning"%>

app/views/universidades/show.html.erb
<p id="notice"><%= notice %></p>