config/routes.rb
Rails.application.routes.draw do
  resources :alunos do
    collection { post :import }
    collection { get :export }
  end
  devise_for :users
  resources :cursos do
    collection { post :import }
    collection { get :export }
  end
  resources :universidades do
    collection { post :import }
    collection { get :export }
  end
  root 'universidades#index'
end

app/models/aluno.rb
class Aluno < ActiveRecord::Base
  belongs_to :curso
  require 'csv'

  validates :nome, presence:true
  validates :email, presence:true
  validates :nota_enade, presence:true


  def self.import(file)

    CSV.foreach(file.path, headers:true) do |row|
        aluno = find_by_id(row["id"]) || new
        aluno.attributes = row.to_hash.slice(*['id','nome','email','nota_enade','curso_id','created_at','updated_at'])
        aluno.save!
    end
  end

  def self.to_csv
      CSV.generate do |csv|
          csv << column_names
          all.each do |curso|
              csv << curso.attributes.values_at(*column_names)
          end
      end
  end
end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  before_action :set_aluno, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  require 'csv'
  # GET /alunos
  # GET /alunos.json
  def index

      if session[:curso_id] == nil
        redirect_to root_url and return
      end

      @q_alunos = Aluno.ransack(params[:q].try(:merge, m:'or'))

      @q_alunos.sorts = 'nome asc' if @q_alunos.sorts.empty?
      @alunos = @q_alunos.result.where "curso_id = #{session[:curso_id]}"
      @mediaCurso = Aluno.where("curso_id = ?",session[:curso_id]).average("nota_enade")
      @alunoMaiorNota = Aluno.where("curso_id = ?",session[:curso_id]).maximum(:nota_enade)
      @alunoMenorNota = Aluno.where("curso_id = ?",session[:curso_id]).minimum(:nota_enade)

      respond_to do |format|
          format.html
          format.csv {send_data @alunos.to_csv}
      end
  end

  def import
      Aluno.import(params[:file])
      redirect_to alunos_url, notice: "Dados do arquivo importados com sucesso!"
  end

  def export
    @alunos = Aluno.where "curso_id = ?", session[:curso_id]
    respond_to do |format|
        format.html
        format.csv {send_data @alunos.to_csv, filename:"alunos_#{session[:curso_nome]}_#{session[:universidade_nome]}.csv"}
    end
  end

  # GET /alunos/1
  # GET /alunos/1.json
  def show
  end

  # GET /alunos/new
  def new
    @aluno = Aluno.new
  end

  # GET /alunos/1/edit
  def edit
  end

  # POST /alunos
  # POST /alunos.json
  def create
    @aluno = Aluno.new(aluno_params)
    @aluno.curso_id = session[:curso_id]
    respond_to do |format|
      if @aluno.save
        format.html { redirect_to alunos_path, notice: 'Aluno cadastrado com sucesso!' }
        format.json { render :show, status: :created, location: @aluno }
      else
        format.html { render :new }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alunos/1
  # PATCH/PUT /alunos/1.json
  def update
    respond_to do |format|
      if @aluno.update(aluno_params)
        format.html { redirect_to alunos_path, notice: 'Aluno atualizado com sucesso!' }
        format.json { render :show, status: :ok, location: @aluno }
      else
        format.html { render :edit }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alunos/1
  # DELETE /alunos/1.json
  def destroy
    @aluno.destroy
    respond_to do |format|
      format.html { redirect_to alunos_url, notice: 'Aluno removido com sucesso!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aluno
      @aluno = Aluno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aluno_params
      params.require(:aluno).permit(:nome, :email, :nota_enade, :curso_id)
    end
end

app/helpers/alunos_helper.rb
module AlunosHelper
  
end

app/views/alunos/_form.html.erb
<%= form_for(@aluno) do |f| %>
  <% if @aluno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aluno.errors.count, "error") %> prohibited this aluno from being saved:</h2>

      <ul>
      <% @aluno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome %><br>
    <%= f.text_field :nome, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :nota_enade %><br>
    <%= f.text_field :nota_enade, class: "form-control" %>
  </div>  
  <div class="form-group">
    <%= f.submit "Confirmar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/alunos/edit.html.erb
<br/>
<div class="alert alert-warning" role="alert">
  <h3>
    <%= "Alterar dados do aluno: #{@aluno.nome}"%>
  </h3>
  <%= "#{session[:curso_nome]} - "%>
  <%= "#{session[:universidade_nome]} - #{session[:universidade_uf]}"%>
</div>

<div class="row">
<div class="col-lg-6 col-xs-6">
  <% if user_signed_in? %>
    <%= link_to 'Remover aluno', @aluno, method: :delete, class: "btn btn-danger", data: { confirm: 'Você tem certeza?' } %>
  <%end%>
  <br/>
  <br/>
</div>
</div>

<%= render 'form' %>

<%= link_to "Voltar", alunos_path, class:"btn btn-warning"%>

app/views/alunos/index.html.erb
<% if flash[:notice] %>
  <br/>
  <div class="alert alert-success" role="alert">
    <%= flash[:notice]%>
  </div>
<%end%>
<br/>
<div class="alert alert-warning" role="alert">
  <h3>
    <%= "#{session[:universidade_nome]} - #{session[:universidade_uf]} -  #{session[:curso_nome]}" %>
  </h3>
</div>

<div class="row">
<div class="col-lg-6 col-xs-6">
  <% if user_signed_in? %>
  <%= link_to 'Cadastrar aluno', new_aluno_path, class: "btn btn-primary"  %>
  <%= link_to 'Download dos alunos (CSV)', export_alunos_path(format: "csv"), class: "btn btn-primary"  %>
  <%end%>
</div>
<div class="col-lg-6 col-xs-6">
  <% if user_signed_in? %>
      <%= form_tag import_alunos_path, multipart:true do %>
        <div class="form-inline">
          <%= file_field_tag :file, class:"form-control" %>
          <%= submit_tag "Importar alunos via CSV", class:"btn btn-primary" %>
        </div>
      <%end%>
  <%end%>
  <br/>
  <br/>
</div>

</div>
<div class="row">
  <div class="col-lg-3 col-xs-6">
  <div class="small-box bg-green">
      <div class="inner">
        <h3><%= "#{session[:curso_nota]}" %><sup style="font-size: 20px"> de 5</sup></h3>
        <p>Nota do curso</p>
      </div>
    </div>
  </div>
  <div class="col-lg-3 col-xs-6">
  <div class="small-box bg-blue">
      <div class="inner">
        <h3><%= @alunoMaiorNota %><sup style="font-size: 20px"> de 5</sup></h3>
        <p>aluno com maior nota</p>
      </div>
    </div>
  </div>
  <div class="col-lg-3 col-xs-6">
  <div class="small-box bg-red">
      <div class="inner">
        <h3><%= @alunoMenorNota %><sup style="font-size: 20px"> de 5</sup></h3>
        <p>aluno com menor nota</p>
      </div>
    </div>
  </div>
  <div class="col-lg-3 col-xs-6">
  <div class="small-box bg-yellow">
      <div class="inner">
        <h3><%= @mediaCurso %><sup style="font-size: 20px"> de 5</sup></h3>
        <p>Média dos alunos</p>
      </div>
    </div>
  </div>
</div>

<div class="row">
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th><%= sort_link(@q_alunos, :nome, 'Nome do aluno') %></th>
      <th><%= sort_link(@q_alunos, :email, 'Email') %></th>
      <th><%= sort_link(@q_alunos, :nota_enade, 'Nota Enade') %></th>
      <% if user_signed_in? %>
      <th>Gerenciar</th>
      <%end%>
    </tr>
  </thead>
  <tbody>
    <% @alunos.each do |aluno| %>
      <tr>
        <td><%= aluno.nome%></td>
        <td><%= aluno.email %></td>
        <td><%= aluno.nota_enade %></td>
        <% if user_signed_in? %>

        <td><%= link_to "Alterar aluno", edit_aluno_path(aluno), class:"btn btn-warning"%></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br/>
<br/>
<%= link_to 'Voltar', cursos_path, class: "btn btn-primary"  %>

app/views/alunos/new.html.erb
<br/>
<div class="alert alert-warning" role="alert">
  <h3>
    <%= "#{session[:curso_nome]} - Cadastrar aluno" %>
  </h3>
  <%= "#{session[:universidade_nome]} - #{session[:universidade_uf]}" %>
</div>


<%= render 'form' %>

<%= link_to "Voltar", alunos_path, class:"btn btn-warning"%>

app/views/alunos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @aluno.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @aluno.email %>
</p>

<p>
  <strong>Nota enade:</strong>
  <%= @aluno.nota_enade %>
</p>

<p>
  <strong>Curso:</strong>
  <%= @aluno.curso %>
</p>

<%= link_to 'Edit', edit_aluno_path(@aluno) %> |
<%= link_to 'Back', alunos_path %>