config/routes.rb
Rails.application.routes.draw do
  resources :alunos do
    collection { post :import }
    collection { get :export }
  end
  devise_for :users
  resources :cursos do
    collection { post :import }
    collection { get :export }
  end
  resources :universidades do
    collection { post :import }
    collection { get :export }
  end
  root 'universidades#index'
end

app/models/curso.rb
class Curso < ActiveRecord::Base
  require 'csv'
  belongs_to :universidade

  validates :nome, presence:true
  validates :nota, presence:true
  validates :media_alunos, presence:true

  def self.import(file)

    CSV.foreach(file.path, headers:true) do |row|
        curso = find_by_id(row["id"]) || new
        curso.attributes = row.to_hash.slice(*['id','nome','uf','nota','media_alunos','created_at','updated_at','universidade_id'])
        curso.save!
    end
  end

  def self.to_csv

      CSV.generate do |csv|
          csv << column_names
          all.each do |curso|
              csv << curso.attributes.values_at(*column_names)
          end
      end

  end
end

app/controllers/cursos_controller.rb
class CursosController < ApplicationController
  before_action :set_curso, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  require 'csv'
  # GET /cursos
  # GET /cursos.json
  def index

    if session[:universidade_id] == nil
      redirect_to root_url and return
    end

    @q_cursos = Curso.ransack(params[:q].try(:merge, m:'or'))

    @q_cursos.sorts = 'nome asc' if @q_cursos.sorts.empty?
    @cursos = @q_cursos.result.where "universidade_id = #{session[:universidade_id]}"

    @cursos.each do |curso|
      curso.media_alunos = Aluno.where("curso_id = ?",curso.id).average("nota_enade")
      curso.save
    end

    @cursoMaiorNota = Curso.where("universidade_id = ?",session[:universidade_id]).maximum(:nota)
    @cursoMenorNota = Curso.where("universidade_id = ?",session[:universidade_id]).minimum(:nota)

    respond_to do |format|
        format.html
        format.csv {send_data @cursos.to_csv}
    end
  end


  def import
      Curso.import(params[:file])
      redirect_to cursos_url, notice: "Dados do arquivo importados com sucesso!"
  end

  def export
    @cursos = Curso.where "universidade_id = ?", session[:universidade_id]
    respond_to do |format|
        format.html
        format.csv {send_data @cursos.to_csv, filename:"cursos_#{session[:universidade_nome]}.csv"}
    end
  end


  # GET /cursos/1
  # GET /cursos/1.json
  def show
    session[:curso_id] = @curso.id
    session[:curso_nome] = @curso.nome
    session[:curso_nota] = @curso.nota
    session[:curso_media] = @curso.media_alunos
    redirect_to alunos_path
  end

  # GET /cursos/new
  def new
    @curso = Curso.new
  end

  # GET /cursos/1/edit
  def edit

  end

  # POST /cursos
  # POST /cursos.json
  def create
    @curso = Curso.new(curso_params)
    @curso.universidade_id = session[:universidade_id]
    @curso.media_alunos = 0
    respond_to do |format|
      if @curso.save
        format.html { redirect_to cursos_path, notice: 'Curso criado com sucesso!' }
        format.json { render :show, status: :created, location: @curso }
      else
        format.html { render :new }
        format.json { render json: @curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cursos/1
  # PATCH/PUT /cursos/1.json
  def update
    respond_to do |format|
      if @curso.update(curso_params)
        format.html { redirect_to cursos_path, notice: 'Curso atualizado com sucesso!' }
        format.json { render :show, status: :ok, location: @curso }
      else
        format.html { render :edit }
        format.json { render json: @curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cursos/1
  # DELETE /cursos/1.json
  def destroy
    @curso.destroy
    respond_to do |format|
      format.html { redirect_to cursos_url, notice: 'Curso removido com sucesso!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_curso
      @curso = Curso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def curso_params
      params.require(:curso).permit(:nome, :nota)
    end
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/views/cursos/_form.html.erb
<%= form_for(@curso) do |f| %>
  <% if @curso.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@curso.errors.count, "error") %> prohibited this curso from being saved:</h2>

      <ul>
      <% @curso.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :nome %><br>
    <%= f.text_field :nome, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :nota %><br>
    <%= f.text_field :nota, class: "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.submit "Confirmar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/cursos/edit.html.erb
<br/>
<div class="alert alert-warning" role="alert">
  <h3>
    <%= "Alterar dados do curso: #{session[:curso_nome]}" %>
  </h3>
  <%= "#{session[:universidade_nome]} - #{session[:universidade_uf]}"%>
</div>

<div class="row">
<div class="col-lg-6 col-xs-6">
  <% if user_signed_in? %>
    <%= link_to 'Remover curso', @curso, method: :delete, class: "btn btn-danger", data: { confirm: 'Você tem certeza?' } %>
    <%= link_to 'Cadastrar aluno', new_aluno_path, class: "btn btn-primary"  %>
  <%end%>
  <br/>
  <br/>
</div>
</div>

<%= render 'form' %>

<%= link_to "Voltar", cursos_path, class:"btn btn-warning"%>

app/views/cursos/index.html.erb
<% if flash[:notice] %>
  <br/>
  <div class="alert alert-success" role="alert">
    <%= flash[:notice]%>
  </div>
<%end%>
<br/>
<div class="alert alert-warning" role="alert">
  <h3>
    <%= "#{session[:universidade_nome]} - #{session[:universidade_uf]}" %>
  </h3>
</div>

<div class="row">
<div class="col-lg-6 col-xs-6">
  <% if user_signed_in? %>
  <%= link_to "Alterar IES", edit_universidade_path(session[:universidade_id]), class:"btn btn-primary"%>
  <%= link_to 'Cadastrar curso', new_curso_path, class: "btn btn-primary"  %>
  <%= link_to 'Download dos cursos (CSV)', export_cursos_path(format: "csv"), class: "btn btn-primary"  %>
  <%end%>
</div>
<div class="col-lg-6 col-xs-6">
  <% if user_signed_in? %>
      <%= form_tag import_cursos_path, multipart:true do %>
        <div class="form-inline">
          <%= file_field_tag :file, class:"form-control" %>
          <%= submit_tag "Importar cursos via CSV", class:"btn btn-primary" %>
        </div>
      <%end%>
  <%end%>
  <br/>
  <br/>
</div>

</div>
<div class="row">
  <div class="col-lg-3 col-xs-6">
  <div class="small-box bg-green">
      <div class="inner">
        <h3><%= "#{session[:universidade_nota_geral]}" %><sup style="font-size: 20px"> de 5</sup></h3>
        <p>Nota Geral</p>
      </div>
    </div>
  </div>
  <div class="col-lg-3 col-xs-6">
  <div class="small-box bg-blue">
      <div class="inner">
        <h3><%= @cursoMaiorNota %><sup style="font-size: 20px"> de 5</sup></h3>
        <p>Curso com maior nota</p>
      </div>
    </div>
  </div>
  <div class="col-lg-3 col-xs-6">
  <div class="small-box bg-red">
      <div class="inner">
        <h3><%= @cursoMenorNota %><sup style="font-size: 20px"> de 5</sup></h3>
        <p>Curso com menor nota</p>
      </div>
    </div>
  </div>
</div>

<%= search_form_for @q_cursos do |f| %>
<div class="form-inline">
  <div class="form-group">
    <%= f.label :nome_cont, "Nome do curso:" %>
    <%= f.search_field :nome_cont, class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :nota_cont, "Nota:" %>
    <%= f.search_field :nota_cont, class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :media_alunos_cont, "Média dos alunos:" %>
    <%= f.search_field :media_alunos_cont, class: "form-control"%>
  </div>
  <%= f.submit "Filtrar", class:"btn btn-primary"%>
</div>
<%end%>
<div class="row">
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th><%= sort_link(@q_cursos, :nome, 'Nome do curso') %></th>
      <th><%= sort_link(@q_cursos, :nota, 'Nota') %></th>
      <th><%= sort_link(@q_cursos, :media_alunos, 'Média dos alunos') %></th>
      <% if user_signed_in? %>
      <th>Detalhes</th>
      <th>Gerenciar</th>
      <%end%>
    </tr>
  </thead>
  <tbody>
    <% @cursos.each do |curso| %>
      <tr>
        <td><%= curso.nome%></td>
        <td><%= curso.nota %></td>
        <td><%= curso.media_alunos%></td>
        <% if user_signed_in? %>
        <td><%= link_to "Detalhes", curso, class:"btn btn-info"%></td>
        <td><%= link_to "Alterar curso", edit_curso_path(curso), class:"btn btn-warning"%></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br/>
<br/>
<%= link_to 'Voltar', universidades_path, class: "btn btn-primary"  %>

app/views/cursos/new.html.erb
<br/>
<div class="alert alert-warning" role="alert">
  <h3>
    <%= "Cadastrar curso" %>
  </h3>
  <%= "#{session[:universidade_nome]} - #{session[:universidade_uf]}" %>
</div>


<%= render 'form' %>

<%= link_to "Voltar", cursos_path, class:"btn btn-warning"%>

app/views/cursos/show.html.erb
<p id="notice"><%= notice %></p>

<%= search_form_for @q_cursos do |f| %>
<div class="form-inline">
  <div class="form-group">
    <%= f.label :nome_cont, "Pesquisar por nome:" %>
    <%= f.search_field :nome_cont, class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :nota_geral_cont, "Pesquisar por nota:" %>
    <%= f.search_field :nota_cont, class: "form-control"%>
  </div>
  <%= f.submit "Filtrar", class:"btn btn-warning"%>
</div>
<%end%>
<h3>
  <%= "#{session[:universidade_nome]} - #{session[:universidade_uf]}" %>
</h3>
<div class="row">
  <div class="col-lg-3 col-xs-6">
  <div class="small-box bg-green">
      <div class="inner">
        <h3><%= "#{session[:universidade_nota_geral]}" %><sup style="font-size: 20px"> de 5</sup></h3>
        <p>Nota Geral</p>
      </div>
    </div>
  </div>
<br/>
<br/>
<br/>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th><%= sort_link(@q_cursos, :nome, 'Nome do curso') %></th>
      <th><%= sort_link(@q_cursos, :nota, 'Nota') %></th>
      <th><%= sort_link(@q_cursos, :media_alunos, 'Média dos alunos') %></th>
    </tr>
  </thead>
  <tbody>
    <% @cursos.each do |curso| %>
      <tr>
        <td><%= curso.nome%></td>
        <td><%= curso.nota %></td>
        <td><%= curso.media_alunos %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br/>
<br/>
<%= link_to 'Voltar', universidades_path, class: "btn btn-primary"  %>